### ISSUE TITLE
Verificare coerenza tra term&conditions pubblicati e nuova edizione della policy

### ISSUE THREAD

**Issue by ecow** [g0v-it/web-budget#19]
Le condizioni pubblicate sono in https://github.com/g0v-it/web-budget/blob/master/src/views/TermsAndConditions.vue

La policy è inm https://sandstorm.copernicani.it/shared/S3TLsXPtdh4hwuJXeVokqFOBhEZgWGTF-ois6aDLiEt

**Comment by luca** [comment]
ho controllato i documenti che hai allegato @ecow e:

1. i termini d'uso mi sembrano identici
2. l'applicazione web NON setta cookies ne propri ne di terze parti quindi non abbiamo bisogno di cookie policy o banner

quindi credo che non ci siano modifiche da fare per ora

**Comment by ecow** [comment]
+1
