### ISSUE TITLE
Chrome va in timeout

### ISSUE THREAD

**Issue by ecow** [g0v-it/web-budget#31]
Se si lascia una finestra di detail attiva per troppo tempo senza fare nulla  chrome va in time out. Non capisco se è un problema legato a twitter o al loop sui capitoli di spesa.

**Comment by luca** [comment]
Il problema era causato dalla lista dei tweet usata in ambiente di test/staging che conteneva un numero enorme di messaggi rallentando il caricamento e funzionamento della pagina.
