### ISSUE TITLE
Problema font nella legenda

### ISSUE THREAD

**Issue by openp2pdesign** [g0v-it/web-budget#33]
La legenda é correttamente configurata con Roboto Mono come font, ma se il font non é installato sul computer non viene caricato nella legenda, é un problema di configurazione del link al Font su Google Font:

![screen shot 2018-11-17 at 16 59 33](https://user-images.githubusercontent.com/1458229/48663004-3a578200-ea8a-11e8-8366-a987d3d37b1f.png)

**Comment by luca** [comment]
closed in `devel`
