### ISSUE TITLE
Se la variazione è zero il colore della bolla dovrebbe essere bianco

### ISSUE THREAD

**Issue by ecow** [g0v-it/web-budget#48]
Invece è verdolino

**Comment by miahmohd** [comment]
invece per le variazioni del 0.0001 o -0.0001 che adesso sono rispettivamente verde e viola e che vengono approssimate a 0 cosa ne facciamo? le mettiamo in bianco o le lasciamo così?

**Comment by ecow** [comment]
Io le lascerei così. In bianco solo se i due valori sono identici.

**Comment by ecow** [comment]
Comunque è abbastanza irrilevante. Se è piu comodo va bene anche portarle a bianco
