### ISSUE TITLE
Le scelte dei filtri devono essere limitate dalle scelte gia effettuate

### ISSUE THREAD

**Issue by luca** [g0v-it/web-budget#6]
> Filtrando per Ministero mi sarei aspettato di trovare solo le Missioni relative… si ritrova la lista completa.

idealmente i valori a disposizione nella selezione dei ministeri e delle missioni dovrebbero essere tali per cui non sia possibile fare una selezione vuota: 

- selezionando un ministero nelle missioni lasciare solo quelle relative a quel ministero
- selezionando una missione lasciare nei ministeri solo quelli che hanno quella missione

**Comment by ecow** [comment]
Questa è da rifiutare. Le missioni non sono da considerare come partizione disgiunta non come selezione gerarchica. La stessa missione può coinvolgere di più ministeri.

**Comment by ecow** [comment]
Le missioni sono un diverso modo di partizionare le azioni.

**Comment by luca** [comment]
e' corretto quello che dici, anche se il tester l'aveva intesa come gerarchica. La mia interpretazione era che si potesse voler fare in modo che i due filtri funzionassero come [facet](https://en.wikipedia.org/wiki/Faceted_search): si possono selezionare in maniera indipendente, ma 
 restringono il campo delle possibili selezioni degli altri parametri.

in ogni caso sarebbe difficile/impossibile da implementare senza usare un indicizzatore come solr o elastic search
