### ISSUE TITLE
bubble graph generale non si ridisegna al resize

### ISSUE THREAD

**Issue by luca** [g0v-it/web-budget#7]
Facendo zoom in e zoom out (Chrome) I frame non si riposizionano automaticamente e le immagini si sovrappongono. Con refresh si aggiusta.

**Comment by ecow** [comment]
Questo so che potrebbe innescareun problema di performance.

Se fosse possibile forzerei il refresh soltanto in caso di cambio significativo delle proporzioni dello schermo (ad esempio  quando si ruota lo schermo del tablet).

**Comment by luca** [comment]
<img width="526" alt="copernicani_budgetgov_-_google_slides_2" src="https://user-images.githubusercontent.com/4583/47029010-d2e8a280-d16a-11e8-821f-bc419f9cd639.png">
<img width="1161" alt="copernicani_budgetgov_-_google_slides" src="https://user-images.githubusercontent.com/4583/47029011-d2e8a280-d16a-11e8-87cc-334d1a7f3c21.png">

Queste le immagini che avevamo ricevuto dal beta tester
